### ISSUE TITLE
the app crashes when you try to find a non-existent document using letters

### ISSUE THREAD

**Issue by greggid** [drunkbatya/EgoDB#1]
the app crashes when you try to find a non-existent document using letters

steps:
enter in the search field "asfdgvqfd"
click on the column "вперёд!!"

result:
site crashed with error 502 (bad getway)

expected result:
window that says:
"В базе данных отсутствуюет то, что вы ищете"

**Comment by drunkbatya** [comment]
Hi, thanks for report. It was fixed in https://github.com/drunkbatya/EgoDB/commit/9b98b806b503980f1e661782659c45b5f736ab5e
